language: c

addons:
  apt:
    packages:
      - cmake
      - valgrind
      - lcov

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - make

jobs:
  include:

    - stage: tests
      name: "Check tests"
      script:
        - ./tests --gtest_shuffle

    - stage: coverage
      name: "Test coverage"
      script:
        - ./tests
        - cd CMakeFiles/tests.dir/tests
        - gcov tests.cpp.gcno
        - lcov --capture --directory ../../ --output-file tests.info
        - genhtml -o ../../../../coverage-report tests.info

    - stage: memcheck
      name: "Memory check"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./tests

    - stage: static_analysis
      name: "Static analysis"
      script:
        - cd ..
        - linters/cppcheck/cppcheck  project --enable=all --error-exitcode=1 -I project/include --suppress=missingIncludeSystem -i project/tests

    - stage: linters
      name: "Linters"
      script:
        - cd ..
        - python2.7 linters/cpplint/cpplint.py --extensions=c include/* src/* tests/*
        - python2.7 linters/cpplint/cpplint.py --extensions=c++ tests/*